-- 코드를 입력하세요
SELECT 
    D.AUTHOR_ID, D.AUTHOR_NAME, C.CATEGORY, C.TOTAL_SALES
FROM (
    SELECT A.AUTHOR_ID, A.CATEGORY, SUM((A.PRICE * B.SALES)) AS TOTAL_SALES
      FROM BOOK AS A JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
      WHERE DATE_FORMAT(B.SALES_DATE, '%Y-%m') = '2022-01'
      GROUP BY A.AUTHOR_ID, A.CATEGORY) AS C JOIN AUTHOR AS D
      ON C.AUTHOR_ID = D.AUTHOR_ID
ORDER BY D.AUTHOR_ID ASC, C.CATEGORY DESC