-- 코드를 작성해주세요

SELECT ID, CASE WHEN QURTER = 1 THEN 'CRITICAL' 
            WHEN QURTER = 2 THEN 'HIGH'
            WHEN QURTER = 3 THEN 'MEDIUM'
            ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QURTER
            FROM ECOLI_DATA
            ORDER BY SIZE_OF_COLONY DESC) AS S
ORDER BY ID ASC