-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY,' ',B.STREET_ADDRESS1,' ',B.STREET_ADDRESS2) AS 전체주소, INSERT(INSERT(B.TLNO, 4,0,'-'), 9,0,'-') AS 전화번호
FROM USED_GOODS_BOARD AS A LEFT JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(A.BOARD_ID) >= 3
ORDER BY B.USER_ID DESC
