-- 코드를 입력하세요
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A RIGHT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.DATETIME IS NOT NULL AND A.DATETIME IS NULL

/*
입양 간 기록은 있지만, 보호소에 들어온 기록은 없는 동물
*/