-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR, COUNT(DISTINCT ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 09 AND HOUR(DATETIME) < 20
GROUP BY HOUR(DATETIME)
ORDER BY 1

/*
각 시간대별로 몇 건이 발생하는지 조회
*/