-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF AS F LEFT JOIN ICECREAM_INFO AS I ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC

-- 총주문량이 3000 보다 높고, 주성분이 과일인 아이스크림의 맛을 총주문량이 큰 순서대로